AccountingApp/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using AccountingApp.DataAccess;
using AccountingApp.Models;
using AccountingApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using WeihanLi.AspNetMvc.MvcSimplePager;
using WeihanLi.Common.Data;
using WeihanLi.Common.Models;
using WeihanLi.EntityFramework;
using WeihanLi.Extensions;
using WeihanLi.Npoi;

namespace AccountingApp.Controllers
{
    public class BillsController : BaseController
    {
        private readonly DalBill repository;

        public BillsController(DalBill billRepository, ILogger<BillsController> logger) : base(logger)
        {
            repository = billRepository;
        }

        // GET: Bill
        public ActionResult Index() => View("NewIndex");

        public async Task<ActionResult> ExportBillsReport()
        {
            var bills = await repository.GetAsync(queryBuilder => queryBuilder
            .WithOrderBy(query => query.OrderBy(x => x.CreatedTime)), HttpContext.RequestAborted);
            if (bills != null && bills.Any())
            {
                return File(bills.ToExcelBytes(), "application/octet-stream", "Bills.xlsx");
            }
            return Content("没有数据需要导出");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<ActionResult> ListAsync(int pageIndex = 1, int pageSize = 20)
        {
            var data = await repository.GetPagedListAsync(queryBuilder => queryBuilder
                     .WithInclude(query => query.Include(x => x.AccountBillType)),
                pageIndex,
                pageSize, HttpContext.RequestAborted);
            return Json(data);
        }

        /// <summary>
        /// 账单列表
        /// </summary>
        /// <param name="pageIndex">页码索引</param>
        /// <param name="pageSize">每页数据量</param>
        /// <param name="filerPersonName">只看谁创建的</param>
        /// <returns></returns>
        [HttpGet]
        [ActionName("BillsList")]
        public async Task<ActionResult> BillsListAsync(int pageIndex = 1, int pageSize = 10, string filerPersonName = "")
        {
            Expression<Func<Bill, bool>> predict = b => true;
            if (!string.IsNullOrWhiteSpace(filerPersonName))
            {
                predict = predict.And(b => b.CreatedBy == filerPersonName);
            }
            var data = await repository.GetPagedListAsync(queryBuilder => queryBuilder.WithPredict(predict).WithOrderBy(q => q.OrderByDescending(x => x.CreatedTime))
            , pageIndex, pageSize);
            return View(data.ToPagedList());
        }

        public ActionResult BillPayItemList(string personName)
        {
            Expression<Func<BillPayItem, bool>> billPayItemPredict = item => true;
            if (!string.IsNullOrWhiteSpace(personName))
            {
                billPayItemPredict.And(b => b.PersonName == personName);
            }
            var billPayRepo = HttpContext.RequestServices.GetService<IEFRepository<AccountingDbContext, BillPayItem>>();
            return Json(billPayRepo.Get(queryBuilderAction: builder => builder
            .WithPredict(billPayItemPredict).WithOrderBy(q => q.OrderByDescending(x => x.CreatedTime))));
        }

        // GET: Bill/Create
        [ActionName("Create")]
        public async Task<ActionResult> CreateAsync()
        {
            var billTypeRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, BillType>>();
            ViewData["BillTypes"] = new BillTypeViewModel(await billTypeRepo.GetAllAsync().ContinueWith(r => r.Result.OrderBy(x => x.TypeName)));
            var userRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, User>>();
            var userNames = await userRepo.GetResultAsync(u => u.Username, builder => builder.WithPredict(s => s.IsActive)
            .WithOrderBy(x => x.OrderBy(a => a.PKID)));
            ViewData["Users"] = userNames;
            return View();
        }

        // POST: Bill/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("BillTitle,BillDescription,BillDetails,BillType,BillFee")]Bill bill)
        {
            var billTypeRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, BillType>>();
            ViewData["BillTypes"] = new BillTypeViewModel(await billTypeRepo.GetAllAsync().ContinueWith(r => r.Result.OrderBy(x => x.TypeName)));
            var userRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, User>>();
            var userNames = await userRepo.GetResultAsync(u => u.Username, builder => builder.WithPredict(s => s.IsActive)
    .WithOrderBy(x => x.OrderBy(a => a.PKID)));
            ViewData["Users"] = userNames;

            try
            {
                if (ModelState.IsValid)
                {
                    var items = bill.BillDetails.JsonToType<List<BillPayItemViewModel>>();
                    if (items.Sum(t => t.PayMoney) != bill.BillFee)
                    {
                        ModelState.AddModelError("BillFee", "每个人实付金额与总金额不符，请检查");
                        ViewData["ErrorMsg"] = "每个人实付金额与总金额不符，请检查";
                        return View();
                    }
                    bill.CreatedBy = User.Identity.Name;
                    var res = await repository.AddAsync(bill);
                    if (res != null)
                    {
                        var billItems = items.Select(t => new BillPayItem { BillId = res.PKID, CreatedBy = User.Identity.Name, PayMoney = t.PayMoney, PersonName = t.PersonName }).Where(b => b.PayMoney > 0).ToList();
                        //保存到数据库
                        var billPayItemRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, BillPayItem>>();
                        await billPayItemRepo.InsertAsync(billItems);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["ErrorMsg"] = "请求参数不合法";
                    return View();
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Bill/Edit/5
        [HttpGet, ActionName("Edit")]
        public async Task<ActionResult> EditAsync(int id)
        {
            var billTypeRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, BillType>>();
            ViewData["BillTypes"] = new BillTypeViewModel(await billTypeRepo.GetAllAsync().ContinueWith(r => r.Result.OrderBy(x => x.TypeName)));
            return View(await repository.FindAsync(id));
        }

        // POST: Bill/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync([Bind("BillTitle,BillDescription,BillType,PKID")]Bill bill)
        {
            try
            {
                bill.UpdatedBy = User.Identity.Name;
                await repository.UpdateAsync(bill, "BillTitle", "BillType", "BillDescription", "UpdatedBy", "UpdatedTime");
                return RedirectToAction("Index");
            }
            catch
            {
                var billTypeRepo = HttpContext.RequestServices.GetRequiredService<IEFRepository<AccountingDbContext, BillType>>();
                ViewData["BillTypes"] = new BillTypeViewModel(await billTypeRepo.GetAllAsync().ContinueWith(r => r.Result.OrderBy(x => x.TypeName)));
                return View();
            }
        }

        /// <summary>
        /// 更新账单状态
        /// </summary>
        /// <param name="id">账单id</param>
        /// <param name="status">账单状态</param>
        /// <returns></returns>
        [HttpPost, ActionName("UpdateBillStatus")]
        public async Task<IActionResult> UpdateBillStatusAsync(int id, int status)
        {
            var result = new JsonResultModel();
            if (id <= 0 || status <= 0)
            {
                result.Status = JsonResultStatus.RequestError;
                result.ErrorMsg = "请求参数异常";
                return Json(result);
            }
            var bill = new Bill { PKID = id, BillStatus = status };
            bill.UpdatedBy = User.Identity.Name;
            await repository.UpdateAsync(bill, b => b.BillStatus);
            result.Status = JsonResultStatus.Success;
            result.ErrorMsg = "";
            return Json(result);
        }

        // GET: Bill/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            var bill = await repository.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            return View(bill);
        }

        // POST: Bill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmedAsync(int id)
        {
            await Task.WhenAll(
                repository.DeleteAsync(m => m.PKID == id, User.Identity.Name),
                HttpContext.RequestServices.GetRequiredService<AccountingRepository<BillPayItem>>()
                .DeleteAsync(t => t.BillId == id, User.Identity.Name));
            return RedirectToAction("Index");
        }
    }
}

AccountingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccountingApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AccountingApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">首页</a></li>
                    <li><a asp-area="" asp-controller="BillTypes" asp-action="Index">账单类型</a></li>
                    <li><a asp-area="" asp-controller="Bills" asp-action="Index">账单管理</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> @(Context.User.Identity.Name) <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("我的账户", "Index", "Account")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("退出登录", "Logout", "Account")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li><a href="/Admin/Account/Login">登录</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AccountingApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/layer/build/layer.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://cdn.bootcss.com/layer/3.0.1/layer.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

AccountingApp/Views/Shared/_PagerPartial.cshtml
@model IPagerModel

@if (Model.TotalCount > 0)
{
    if (Model.PageCount < 2 && Model.PagingDisplayMode == PagingDisplayMode.IfNeeded)
    {

    }
    else
    {
        int offset = (Model.GroupSize) / 2, temp = 0;
        int pageStart = Model.PageNumber - offset, pageEnd = Model.PageNumber + offset, curPage = 0;
        <div style="text-align:center">
            <nav>
                <ul class="pagination">
                    @if (Model.HasPreviousPage)
                    {
                        <li><a href='@Model.OnPageChange(Model.PageNumber - 1)' aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    }
                    else
                    {
                        <li class="disabled"><a href="javascript:void(0)" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    }
                    @if (pageStart <= 1 && pageEnd >= Model.PageCount)
                    {
                        for (int i = 0; i <= Model.GroupSize; i++)
                        {
                            curPage = pageStart + i;
                            if ((curPage >= 1) && (curPage <= Model.PageCount))
                            {
                                if (curPage == Model.PageNumber)
                                {
                                    <li class="active"><a href="javascript:void(0)">@Model.PageNumber<span class="sr-only">(current)</span></a></li>
                                }
                                else
                                {
                                    <li><a href='@Model.OnPageChange(curPage)'> @curPage <span class="sr-only"> @curPage </span></a> </li>
                                }
                            }
                        }
                    }
                    else
                    {
                        if (pageStart > 1)
                        {
                            <li><a href='@Model.OnPageChange(1)'>1<span class="sr-only">1</span></a></li>
                            <li><a href='@Model.OnPageChange(2)'>2<span class="sr-only">1</span></a></li>
                            <li class="disbaled"><a href="javascript:void(0)">...<span class="sr-only">...</span></a></li>
                            temp = Model.PageNumber - offset / 2;
                            curPage = temp;
                            for (int i = 0; i <= offset / 2 + 1; i++)
                            {
                                curPage = temp + i;
                                if ((curPage >= 1) && (curPage <= Model.PageCount))
                                {
                                    if (curPage == Model.PageNumber)
                                    {
                                        <li class="active"><a href="javascript:void(0)">@Model.PageNumber<span class="sr-only">(current)</span></a></li>
                                        break;
                                    }
                                    else
                                    {
                                        <li><a href='@Model.OnPageChange(curPage)'> @curPage <span class="sr-only"> @curPage </span></a> </li>
                                    }
                                }
                            }
                        }
                        else
                        {
                            for (int i = 0; i <= offset; i++)
                            {
                                curPage = pageStart + i;
                                if ((curPage >= 1) && (curPage <= Model.PageCount))
                                {
                                    if (curPage == Model.PageNumber)
                                    {
                                        <li class="active"><a href="javascript:void(0)">@Model.PageNumber<span class="sr-only">(current)</span></a></li>
                                        break;
                                    }
                                    else
                                    {
                                        <li><a href='@Model.OnPageChange(curPage)'> @curPage <span class="sr-only"> @curPage </span></a> </li>
                                    }
                                }
                            }
                        }
                        if (pageEnd < Model.PageCount)
                        {
                            temp = Model.PageNumber + 1;
                            curPage = temp;
                            for (int i = 0; i <= offset / 2 && curPage <= Model.PageCount; i++)
                            {
                                curPage = temp + i;
                                if ((curPage >= 1) && (curPage <= Model.PageCount))
                                {
                                    <li><a href='@Model.OnPageChange(curPage)'> @curPage <span class="sr-only"> @curPage </span></a> </li>
                                }
                            }
                            <li class="disbaled"><a href="javascript:void(0)">...<span class="sr-only">...</span></a></li>
                            <li><a href='@Model.OnPageChange(Model.PageCount - 1)'>@(Model.PageCount - 1)<span class="sr-only">@(Model.PageCount - 1)</span></a></li>
                            <li><a href='@Model.OnPageChange(Model.PageCount)'>@Model.PageCount<span class="sr-only">@Model.PageCount</span></a></li>
                        }
                        else
                        {
                            curPage = Model.PageNumber;
                            for (int i = 0; i <= offset && curPage <= Model.PageCount; i++)
                            {
                                curPage++;
                                if ((curPage >= 1) && (curPage <= Model.PageCount))
                                {
                                    if (curPage == Model.PageNumber)
                                    {
                                        <li class="active"><a href="javascript:void(0)">@Model.PageNumber<span class="sr-only">(current)</span></a></li>
                                        break;
                                    }
                                    else
                                    {
                                        <li><a href='@Model.OnPageChange(curPage)'> @curPage <span class="sr-only"> @curPage </span></a> </li>
                                    }
                                }
                            }
                        }
                    }

                    @if (Model.HasNextPage)
                    {
                        <li><a href='@Model.OnPageChange(Model.PageNumber + 1)' aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    }
                    else
                    {
                        <li class="disabled"><a href="javascript:void(0)" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    }
                </ul>
            </nav>
            <div>
                <span>每页有<strong>@Model.PageSize</strong>条数据，一共有<strong>@Model.PageCount</strong>页，总计<strong>@Model.TotalCount</strong>条数据</span>
            </div>
        </div>
    }
}